import { getAccessToken } from '../auth/auth-storage'
export type AttendanceFilters={period:'daily'|'weekly'|'monthly'|'semester';date:string;weekStart:string;year:number;month:number;academicTermId:string;q:string;role:string;purpose:string;presence:string;page:number;limit:number}
export type AttendanceRow={id:number;visitor_name:string;school_id:string;email:string;role:string;attendance_date:string;time_in:string;time_out:string|null;purpose:string;presence:'Inside'|'Exited'}
export type AttendanceSummary={total_visits:number;unique_visitors:number;currently_inside:number;average_visit:string|null;peak_hour:string|null;purpose_breakdown:Array<{label:string;count:number}>;role_breakdown:Array<{label:string;count:number}>;range:{from:string;to:string;label:string}}
export type AcademicTerm={academic_term_id:number;academic_year:string;term_name:string;starts_on:string;ends_on:string;is_active:number}
export type Pagination={page:number;limit:number;total:number;total_pages:number}
function params(f:AttendanceFilters){const q=new URLSearchParams({period:f.period,page:String(f.page),limit:String(f.limit)});if(f.q)q.set('q',f.q);if(f.role)q.set('role',f.role);if(f.purpose)q.set('purpose',f.purpose);if(f.presence)q.set('presence',f.presence);if(f.period==='daily'&&f.date)q.set('date',f.date);if(f.period==='weekly'&&f.weekStart)q.set('week_start',f.weekStart);if(f.period==='monthly'){q.set('year',String(f.year));q.set('month',String(f.month))}if(f.period==='semester'&&f.academicTermId)q.set('academic_term_id',f.academicTermId);return q}
function headers(accept='application/json'){const h=new Headers({Accept:accept}),token=getAccessToken();if(token)h.set('Authorization',`Bearer ${token}`);return h}
async function json<T>(url:string){const r=await fetch(url,{credentials:'include',headers:headers()});const p=await r.json() as {data?:T;message?:string;meta?:{pagination?:Pagination}};if(!r.ok)throw new Error(p.message??'Unable to load attendance data.');return{data:p.data as T,meta:p.meta}}
export const attendanceApi={terms:async()=> (await json<AcademicTerm[]>('/api/v1/admin/attendance/academic-terms')).data,summary:async(f:AttendanceFilters)=>(await json<AttendanceSummary>(`/api/v1/admin/attendance/summary?${params(f)}`)).data,logs:async(f:AttendanceFilters)=>{const result=await json<AttendanceRow[]>(`/api/v1/admin/attendance/logs?${params(f)}`);return{rows:result.data,pagination:result.meta?.pagination??{page:1,limit:f.limit,total:0,total_pages:0}}},downloadPdf:async(f:AttendanceFilters)=>{const r=await fetch(`/api/v1/admin/attendance/report.pdf?${params(f)}`,{credentials:'include',headers:headers('application/pdf')});if(!r.ok){const p=await r.json().catch(()=>({})) as {message?:string};throw new Error(p.message??'Unable to generate attendance report.')}if(!(r.headers.get('content-type')??'').includes('application/pdf'))throw new Error('The server returned an invalid report file.');const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`smartlib-attendance-${f.period}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}}
