import { ArrowRight, Bell, BookMarked, BookOpen, CalendarClock, CheckCircle2, Clock3, Eye, MapPin, PhilippinePeso, Printer, RotateCcw, Search, ShoppingBag, Sparkles } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Button, CardLink, PageHeader, SectionCard, StatCard, StatusBadge } from '../../components/ui'
import { dashboardApi } from './dashboard-api'
import type { UserDashboardData } from './types'
import { BookCoverThumbnail } from '../catalog/BookCoverThumbnail'
import { BookOverview } from '../catalog/BookOverview'
import { fetchBookOverview } from '../catalog/book-catalog-api'
import { validateBookCartAddition } from '../catalog/book-cart'
import { useBookCart } from '../catalog/book-cart-store'
import type { BookCatalogItem } from '../catalog/book-catalog-types'
import type { AuthRole } from '../auth/auth-storage'

const peso=(value:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(value)
const first=(name:string)=>name.trim().split(/\s+/)[0]||'Library user'
const dayNames=['','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

export function UserDashboardPage(){
  const[data,setData]=useState<UserDashboardData|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true)
  const[selectedTitleId,setSelectedTitleId]=useState<number|null>(null);const[borrowingTitleId,setBorrowingTitleId]=useState<number|null>(null);const[notice,setNotice]=useState('')
  const{items:cart,addItem}=useBookCart();const cartIds=useMemo(()=>new Set(cart.map(item=>item.titleId)),[cart])
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await dashboardApi.user())}catch(value){setError(value instanceof Error?value.message:'The dashboard could not be loaded.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  if(!data&&loading)return <div className="space-y-4"><div className="h-10 w-72 animate-pulse rounded-xl bg-[#003399]/10"/><div className="h-48 animate-pulse rounded-3xl bg-[#003399]/10"/></div>
  if(!data)return <SectionCard className="p-8 text-center"><p className="font-display text-xl font-bold text-[#003399]">Dashboard unavailable</p><p className="mt-2 text-sm text-[#003399]/65">{error}</p><Button className="mt-5" onClick={()=>void load()}><RotateCcw size={16}/>Try again</Button></SectionCard>
  const prefix=data.user.role==='Faculty'?'/faculty':'/student',limitNote=data.summary.borrowingLimit===null?'No fixed borrowing limit':`${Math.max(0,data.summary.borrowingLimit-data.summary.activeLoans)} slot${Math.max(0,data.summary.borrowingLimit-data.summary.activeLoans)===1?'':'s'} remaining`
  const occupancyPercent=Math.min(100,Math.round(data.occupancy.current/data.occupancy.capacity*100));const cleared=data.summary.clearanceStatus==='Cleared';const today=manilaDay();const todaySchedule=data.profile.schedule.find(item=>item.day===today)
  const addCatalogBook=(book:BookCatalogItem)=>{
    const validation=validateBookCartAddition({role:data.user.role as AuthRole,activeBookCount:data.summary.activeBookCount,selectedBookCount:cart.length,alreadySelected:cartIds.has(book.titleId)})
    if(!validation.allowed){setNotice('');setError(validation.message??'This book cannot be added to the cart.');return}
    if(!cartIds.has(book.titleId))addItem(book);setError('');setNotice(validation.message??`${book.title} was added to your borrow cart.`)
  }
  const borrowRecommendation=async(titleId:number)=>{
    setBorrowingTitleId(titleId);setError('');setNotice('')
    try{addCatalogBook(await fetchBookOverview(titleId))}catch(reason){setError(reason instanceof Error?reason.message:'The book could not be added to the cart.')}finally{setBorrowingTitleId(null)}
  }
  const recommendationsPanel=<SectionCard className="mb-5 p-5">
    <div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#003399]/45">Recommended for {data.user.program??'you'}</p><h2 className="mt-1 font-display text-lg font-bold text-[#003399]">Available to borrow</h2></div><Link to={`${prefix}/catalog`}><CardLink>View all</CardLink></Link></div>
    {data.recommendations.length?<div className="grid gap-5 sm:grid-cols-3">{data.recommendations.map(book=><article key={book.id} className="flex min-w-0 flex-col"><div className="flex justify-center"><BookCoverThumbnail title={book.title} coverImagePath={book.coverPath} className="h-48 w-32 rounded-xl border border-[#003399]/15 shadow-[0_6px_16px_rgba(0,51,153,0.12)] sm:h-56 sm:w-40"/></div><p className="mt-2 line-clamp-2 text-xs font-bold text-[#003399]">{book.title}</p><p className="mt-0.5 truncate text-[11px] text-[#003399]/45">{book.author}</p><p className="mt-1 text-[10px] font-semibold text-[#003399]/65">{book.availableCopies} available</p><div className="mt-auto grid grid-cols-2 gap-2 pt-3"><button type="button" onClick={()=>setSelectedTitleId(book.id)} className="inline-flex h-9 items-center justify-center gap-1 rounded-xl border border-[#003399]/20 bg-[#FFFFFF] px-2 text-[11px] font-bold text-[#003399]"><Eye size={14}/>View details</button><button type="button" disabled={cartIds.has(book.id)||borrowingTitleId===book.id} onClick={()=>void borrowRecommendation(book.id)} className="inline-flex h-9 items-center justify-center gap-1 rounded-xl bg-[#003399] px-2 text-[11px] font-bold text-[#FFFFFF] disabled:opacity-50"><ShoppingBag size={14}/>{cartIds.has(book.id)?'In cart':borrowingTitleId===book.id?'Adding…':'Borrow'}</button></div></article>)}</div>:<Empty text="No available recommendations right now."/>}
    <div className="mt-5 flex flex-wrap gap-3 border-t border-[#003399]/10 pt-4"><Link to={`${prefix}/catalog`}><Button><Search size={16}/>Browse catalog</Button></Link><Link to={`${prefix}/cart`}><Button variant="secondary"><ShoppingBag size={16}/>Borrow cart ({cart.length})</Button></Link><Button variant="secondary" onClick={()=>void load()}><RotateCcw size={16}/>Refresh dashboard</Button></div>
  </SectionCard>
  return <>
    <PageHeader eyebrow={`${data.user.role} workspace`} title={`Good day, ${first(data.user.name)}!`}/>
    {error?<div role="alert" className="mb-5 rounded-2xl bg-[#FFF200] px-4 py-3 text-sm font-semibold text-[#003399]">{error}</div>:null}{notice?<div role="status" className="mb-5 rounded-2xl bg-[#003399] px-4 py-3 text-sm font-semibold text-[#FFFFFF]">{notice}</div>:null}
    <section className="relative mb-5 overflow-hidden rounded-3xl bg-[#003399] p-6 text-white shadow-xl shadow-[#003399]/10 sm:p-8">
      <div className="absolute -right-20 -top-24 h-64 w-64 rounded-full border-[42px] border-white/5"/><div className="relative z-10 grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-semibold ring-1 ring-white/10"><Sparkles size={14} className="text-[#FFF200]"/>Your library, made smarter</div><h2 className="max-w-2xl font-display text-2xl font-bold sm:text-3xl">Your books, requests, updates, and library visit in one place.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/80">{data.profile.information??'Check your account and explore available library resources.'}</p><div className="mt-5 flex flex-wrap gap-3"><Link to={`${prefix}/catalog`}><Button className="bg-[#FFF200] text-[#003399]">Explore catalog<ArrowRight size={16}/></Button></Link><Link to={`${prefix}/research`}><Button variant="ghost" className="bg-white/10 text-white hover:bg-white/15 hover:text-white">Browse research</Button></Link></div></div>
      <div className="grid grid-cols-2 gap-3 lg:w-72"><div className="rounded-2xl bg-white/10 p-4 ring-1 ring-white/10"><p className="text-xs text-white/70">Library occupancy</p><p className="mt-1 text-2xl font-bold">{data.occupancy.current}<span className="text-sm font-medium text-white/60"> / {data.occupancy.capacity}</span></p><div className="mt-3 h-1.5 rounded-full bg-white/10"><div style={{width:`${occupancyPercent}%`}} className="h-full rounded-full bg-[#FFF200]"/></div></div><div className="rounded-2xl bg-white/10 p-4 ring-1 ring-white/10"><p className="text-xs text-white/70">Clearance status</p><div className="mt-2 flex items-center gap-2 text-lg font-bold"><CheckCircle2 size={20} className="text-[#FFF200]"/>{data.summary.clearanceStatus}</div><p className="mt-3 text-xs text-white/60">{cleared?'No clearance block':'Resolve account obligations'}</p></div></div></div>
    </section>
    <div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Active loans" value={data.summary.activeLoans} icon={BookOpen} tone="blue"/><StatCard label="Reservations" value={data.summary.activeReservations} icon={BookMarked} tone="violet"/><StatCard label="Unread updates" value={data.summary.unreadNotifications} icon={Bell} tone="orange"/><StatCard label="Outstanding fines" value={peso(data.summary.outstandingFines)} icon={PhilippinePeso} tone={data.summary.outstandingFines?'red':'emerald'}/></div>
    {recommendationsPanel}
    <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]">
      <SectionCard className="p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#003399]/45">Current loan</p><h2 className="mt-1 font-display text-lg font-bold text-[#003399]">Return reminder</h2></div>{data.currentLoan?<StatusBadge status={data.currentLoan.status}/>:null}</div>{data.currentLoan?<div className="flex gap-4 rounded-2xl bg-[#003399]/5 p-4"><BookCoverThumbnail title={data.currentLoan.title} coverImagePath={data.currentLoan.coverPath} className="h-28 w-20 rounded-xl border border-[#003399]/15 shadow-[0_4px_12px_rgba(0,51,153,0.12)]"/><div className="min-w-0 flex-1"><h3 className="font-display font-bold text-[#003399]">{data.currentLoan.title}</h3><p className="mt-0.5 text-sm text-[#003399]/65">{data.currentLoan.author}</p><div className="mt-4 grid gap-2 text-xs sm:grid-cols-2"><div className="flex items-center gap-2 text-[#003399]/65"><CalendarClock size={15}/>Due {data.currentLoan.dueAt}</div><div className="flex items-center gap-2 text-[#003399]/65"><MapPin size={15}/>{data.currentLoan.shelfLocation||data.currentLoan.barcode}</div></div></div></div>:<Empty text="You have no active borrowed books."/>}<p className="mt-3 text-xs text-[#003399]/45">{limitNote}</p></SectionCard>
      <SectionCard className="p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#003399]/45">Print service</p><h2 className="mt-1 font-display text-lg font-bold text-[#003399]">Latest request</h2></div><Printer size={21} className="text-[#003399]"/></div>{data.printRequest?<div className="rounded-2xl border border-[#003399]/15 bg-[#003399]/5 p-4"><div className="flex justify-between gap-3"><div><p className="line-clamp-1 font-semibold text-[#003399]">{data.printRequest.fileName}</p><p className="mt-1 text-xs text-[#003399]/65">{data.printRequest.copies} copies · {data.printRequest.printType}</p></div><StatusBadge status={data.printRequest.status}/></div><div className="mt-4 flex items-end justify-between"><p className="text-lg font-bold text-[#003399]">{peso(data.printRequest.cost)}</p>{data.user.role==='Student'?<Link to="/student/printing"><CardLink>View request</CardLink></Link>:null}</div></div>:<Empty text="No active print request."/>}</SectionCard>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-3">
      <SectionCard className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#003399]/45">Reservation</p><h2 className="mt-1 font-display text-lg font-bold text-[#003399]">Queue and pickup</h2>{data.reservation?<div className="mt-4 flex gap-4 rounded-xl bg-[#003399]/5 p-4"><BookCoverThumbnail title={data.reservation.title} coverImagePath={data.reservation.coverPath} className="h-28 w-20 shrink-0 rounded-xl border border-[#003399]/15 shadow-[0_4px_12px_rgba(0,51,153,0.12)]"/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="line-clamp-2 font-semibold text-[#003399]">{data.reservation.title}</p><StatusBadge status={data.reservation.status}/></div><p className="mt-3 text-sm text-[#003399]/65">Queue position <strong>#{data.reservation.queuePosition}</strong></p>{data.reservation.pickupDeadline?<p className="mt-1 text-xs text-[#003399]/55">Pickup by {data.reservation.pickupDeadline}</p>:null}</div></div>:<Empty text="No active reservation."/>}</SectionCard>
      <SectionCard className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#003399]/45">Latest update</p><h2 className="mt-1 font-display text-lg font-bold text-[#003399]">Notifications</h2>{data.latestNotification?<div className="mt-4"><p className="font-semibold text-[#003399]">{data.latestNotification.title}</p><p className="mt-2 line-clamp-3 text-sm leading-6 text-[#003399]/65">{data.latestNotification.message}</p><Link to={`${prefix}/notifications`} className="mt-3 inline-block"><CardLink>View notifications</CardLink></Link></div>:<Empty text="You are all caught up."/>}</SectionCard>
      <SectionCard className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#003399]/45">Library information</p><h2 className="mt-1 font-display text-lg font-bold text-[#003399]">Hours and schedule</h2><div className="mt-4 flex items-start gap-3"><Clock3 size={19} className="mt-0.5 text-[#003399]"/><div><p className="text-sm font-semibold text-[#003399]">{dayNames[today]}: {todaySchedule?.isOpen?`${todaySchedule.opensAt} – ${todaySchedule.closesAt}`:'Closed'}</p>{data.profile.nextClosure?<p className="mt-2 text-xs text-[#003399]/65">Next closure: {data.profile.nextClosure.date} · {data.profile.nextClosure.reason}</p>:<p className="mt-2 text-xs text-[#003399]/65">No upcoming closure is posted.</p>}</div></div>{data.profile.mapPath?<a className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-[#003399]" href={data.profile.mapPath}><MapPin size={15}/>View library map</a>:null}</SectionCard>
    </div>
    {data.announcement?<SectionCard className="mt-5 border-[#FFF200] bg-[#FFF200]/20 p-5"><div className="flex items-start gap-3"><Bell className="mt-0.5 text-[#003399]" size={20}/><div><p className="text-xs font-bold uppercase tracking-wider text-[#003399]/55">Library announcement · {data.announcement.priority}</p><h2 className="mt-1 font-display text-lg font-bold text-[#003399]">{data.announcement.title}</h2><p className="mt-2 text-sm leading-6 text-[#003399]/70">{data.announcement.message}</p></div></div></SectionCard>:null}
    <div className="mt-5">
      <SectionCard className="p-5"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-[#003399]/45">Recent borrowing</p><h2 className="mt-1 font-display text-lg font-bold text-[#003399]">History preview</h2></div><div className="divide-y divide-[#003399]/10">{data.recentHistory.map(item=><div key={item.id} className="flex items-center justify-between gap-3 py-3"><div className="flex min-w-0 items-center gap-3"><BookCoverThumbnail title={item.title} coverImagePath={item.coverPath} className="h-16 w-11 shrink-0 rounded-lg border border-[#003399]/15 shadow-[0_2px_8px_rgba(0,51,153,0.10)]"/><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#003399]">{item.title}</p><p className="mt-1 text-[11px] text-[#003399]/45">{item.eventAt}</p></div></div><StatusBadge status={item.status}/></div>)}{!data.recentHistory.length?<Empty text="No borrowing history yet."/>:null}</div><Link to={`${prefix}/borrowing`}><CardLink>View full history</CardLink></Link></SectionCard>
    </div>
    {selectedTitleId!==null?<BookOverview titleId={selectedTitleId} role={data.user.role as AuthRole} activeBookCount={data.summary.activeBookCount} selectedBookCount={cart.length} alreadySelected={cartIds.has(selectedTitleId)} onAddToCart={addCatalogBook} onClose={()=>setSelectedTitleId(null)}/>:null}
  </>
}

function manilaDay(){const short=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Manila',weekday:'short'}).format(new Date());return ({Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7} as Record<string,number>)[short]??1}
function Empty({text}:{text:string}){return <p className="py-6 text-center text-sm text-[#003399]/45">{text}</p>}
