flowchart TB
  P1[Users_MIS]
  P2[Create_or_Edit_Account]
  P3[Assign_Role]
  P4[Activate_Deactivate_Archive]
  P5[Attendance_Monitoring]
  P6[Scan_Student_Faculty_QR]
  P7[Update_Visit_Logs]
  P8[Clearance_Module]
  P9[Review_Standing]
  P10[Authorized_Override]
  P11[Announcements]
  P12[Publish_Notice]
  P13[Reports]
  P1 --> P2
  P2 --> P3
  P3 --> P4
  P5 --> P6
  P6 --> P7
  P8 --> P9
  P9 --> P10
  P11 --> P12
  P13 --> P13
