flowchart TB
  I1[Books_and_Research_Module]
  I2[Add_or_Edit_Title]
  I3[Register_Physical_Copies]
  I4[Barcode_ISBN_Scan]
  I5[Manage_Categories]
  I6[Inventory_Dashboard]
  I7[Update_Condition_Availability]
  I8[Thesis_Inventory]
  I9[Export_CSV_PDF]
  I10[Book_Archive]
  I1 --> I2
  I1 --> I3
  I1 --> I4
  I1 --> I5
  I1 --> I6
  I6 --> I7
  I6 --> I8
  I6 --> I9
  I1 --> I10
